version: "3"
services:
  mongo:
    image: mongo
    container_name: ZXVenturesCodeChallengeBackend-php-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  app:
    build: .
    container_name: ZXVenturesCodeChallengeBackend-php-app
    restart: always
    ports:
      - 8000:80
    depends_on:
      - mongo
    environment:
      ENVIRONMENT: development
